---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kalkulator-kalkulator-io-v1-sum
  failurePolicy: Fail
  name: vsum.kb.io
  rules:
  - apiGroups:
    - kalkulator.kalkulator.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sums
  sideEffects: None
