---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kalkulator.kalkulator.io
  resources:
  - sums
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kalkulator.kalkulator.io
  resources:
  - sums/finalizers
  verbs:
  - update
- apiGroups:
  - kalkulator.kalkulator.io
  resources:
  - sums/status
  verbs:
  - get
  - patch
  - update
